name: ML Pipeline

on:
  push:

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean mlruns
        run: rm -rf mlruns

      - name: Train model
        run: python train.py

      - name: Show mlruns structure
        run: ls -R mlruns

      - name: Upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

      - name: Upload MLflow data
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns   

  deploy:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Download model info
        uses: actions/download-artifact@v4
        with:
          name: model-info

      - name: Download MLflow data
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns 

      - name: Debug files
        run: |
          echo "Model Info:"
          cat model_info.txt
          echo "MLruns structure:"
          ls -R mlruns

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install mlflow

      - name: Check threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"